# Generated by Django 4.0.3 on 2022-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='choices',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
